[package]
name = "cesscrypto"
description = "FFI Interface to CESS Proofs"
version = "0.1.0"
authors = []
license = "MIT OR Apache-2.0"
repository = "https://github.com/CESSProject/cess-ffi"
readme = "README.md"
edition = "2018"
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
bls-signatures = { version = "0.11.0", default-features = false, features = ["blst"] }
blstrs = "0.4"
byteorder = "1.2"
drop_struct_macro_derive = "0.5.0"
ff = { version = "0.3.1", package = "fff" }
ffi-toolkit = "0.5.0"
filepath = "0.1.1"
group = "0.11"
libc = "0.2.58"
log = "0.4.7"
fil_logger = "0.1.0"
rand = "0.8"
rand_chacha = "0.3.1"
rayon = "1.2.1"
anyhow = "1.0.23"
bellperson = { version = "0.18", default-features = false }
serde_json = "1.0.46"
rust-gpu-tools = { version = "0.5", default-features = false }
cess-sp-porep = { version = "~0.1.2", default-features = false }

[dependencies.cess-proving-system-api]
package = "cess-proving-system-api"
version = "0.1.2"
default-features = false

[build-dependencies]
cbindgen = "= 0.14.0"

[dev-dependencies]
tempfile = "3.0.8"

[features]
default = ["opencl", "multicore-sdr" ]
blst-portable = ["bls-signatures/blst-portable", "blstrs/portable"]
opencl = ["cess-proving-system-api/opencl", "bellperson/opencl", "cess-sp-porep/opencl", "rust-gpu-tools/opencl"]
cuda = ["cess-proving-system-api/cuda", "bellperson/cuda", "cess-sp-porep/cuda", "rust-gpu-tools/cuda"]
multicore-sdr = ["cess-sp-porep/multicore-sdr"]
