[cessChain]
# CESS chain address
rpcAddr = "ws://106.15.44.155:9949/"

[schedulerData]
# The IP address of the machine's public network used by the mining program.
serviceIpAddress            = ""
# Port number monitored by the mining program
servicePort                 = ""
# Public key of income account.
incomeAccountPubkey    = ""
# Phrase words or seeds for identity accounts.
idAccountPhraseOrSeed  = ""