[CessChain]
# CESS chain address
ChainAddr = ""

[SchedulerInfo]
# The IP address of the machine's public network used by the scheduler program.
ServiceAddr    = ""
# Port number monitored by the scheduler program
ServicePort    = ""
# Phrase words or seeds for identity accounts.
TransactionPrK = ""